- host: localhost
  connection: local
  become: true

  pre_tasks:
  - name: DNF update the system
    dnf:
      update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml

