- host: localhost
  connection: local
  become: true

  task:
  - name: DNF update the system
    dnf:
      name: "*"
      state: latest
  - name: Enable RPM Free & non-free repository
    dnf:
      name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      state: present
  - name: Enable RPM non-Free repository
    dnf:
      name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
      state: present
  - name: Install Media Codecs
    dnf:
      name: [gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel", lame\* --exclude=lame-devel]
      state: present 
  - name: Multimedia Group Upgrade
    dnf:
      name: @Multimedia
      state: present
